# Form implementation generated from reading ui file 'D:\24. Tư duy lập trình\class10k\class10k\course1\HousePricePrediction\ui\MainWindowPrediction.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(991, 787)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidgetHouse = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidgetHouse.setGeometry(QtCore.QRect(10, 70, 911, 661))
        self.tableWidgetHouse.setObjectName("tableWidgetHouse")
        self.tableWidgetHouse.setColumnCount(7)
        self.tableWidgetHouse.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHouse.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHouse.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHouse.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHouse.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHouse.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHouse.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetHouse.setHorizontalHeaderItem(6, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 991, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidgetHouse.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Avg. Area Income"))
        item = self.tableWidgetHouse.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Avg. Area House Age"))
        item = self.tableWidgetHouse.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Avg. Area Number of Rooms"))
        item = self.tableWidgetHouse.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Avg. Area Number of Bedrooms"))
        item = self.tableWidgetHouse.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Area Population"))
        item = self.tableWidgetHouse.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Real Price"))
        item = self.tableWidgetHouse.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Predicted Price"))
