# Form implementation generated from reading ui file 'D:\24. Tư duy lập trình\class10k\class10k\course1\o_2024y_10m_25d\Quanly_sanpham\ui\MainWindowLoginUI.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(735, 419)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\24. Tư duy lập trình\\class10k\\class10k\\course1\\o_2024y_10m_25d\\Quanly_sanpham\\ui\\../images/jinopass.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(203, 220, 235);\n"
"background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 50, 391, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(19, 62, 135);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 140, 81, 16))
        self.label_2.setObjectName("label_2")
        self.lineEditUserName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditUserName.setGeometry(QtCore.QRect(150, 140, 261, 22))
        self.lineEditUserName.setObjectName("lineEditUserName")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 170, 81, 20))
        self.label_3.setObjectName("label_3")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditPassword.setGeometry(QtCore.QRect(150, 170, 261, 22))
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.checkBoxLuu = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBoxLuu.setGeometry(QtCore.QRect(240, 210, 171, 20))
        self.checkBoxLuu.setObjectName("checkBoxLuu")
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonLogin.setGeometry(QtCore.QRect(220, 240, 93, 28))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\24. Tư duy lập trình\\class10k\\class10k\\course1\\o_2024y_10m_25d\\Quanly_sanpham\\ui\\../images/icon_login.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonLogin.setIcon(icon1)
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 240, 93, 28))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:\\24. Tư duy lập trình\\class10k\\class10k\\course1\\o_2024y_10m_25d\\Quanly_sanpham\\ui\\../images/icon_out.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 110, 131, 16))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(450, 60, 231, 211))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("D:\\24. Tư duy lập trình\\class10k\\class10k\\course1\\o_2024y_10m_25d\\Quanly_sanpham\\ui\\../images/jinopass.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 735, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEditUserName, self.lineEditPassword)
        MainWindow.setTabOrder(self.lineEditPassword, self.checkBoxLuu)
        MainWindow.setTabOrder(self.checkBoxLuu, self.pushButtonLogin)
        MainWindow.setTabOrder(self.pushButtonLogin, self.pushButton_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hệ thống quản lý sách pass"))
        self.label.setText(_translate("MainWindow", "ĐĂNG NHẬP HỆ THỐNG QUẢN LÝ BÁN HÀNG"))
        self.label_2.setText(_translate("MainWindow", "User name:"))
        self.lineEditUserName.setText(_translate("MainWindow", "admin"))
        self.label_3.setText(_translate("MainWindow", "Password:"))
        self.lineEditPassword.setText(_translate("MainWindow", "2004"))
        self.checkBoxLuu.setText(_translate("MainWindow", "Lưu thông tin đăng nhập"))
        self.pushButtonLogin.setText(_translate("MainWindow", "Đăng nhập"))
        self.pushButtonLogin.setShortcut(_translate("MainWindow", "Return"))
        self.pushButton_2.setText(_translate("MainWindow", "Thoát"))
        self.label_4.setText(_translate("MainWindow", "Thông tin đăng nhập"))
